@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

class Cell {
Object[] elementData
Object[] kekw
is_available()
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml